name: Generate API docs and publish to Github Pages

env:
  BRANCHLIST: "MOODLE_311_STABLE MOODLE_400_STABLE MOODLE_401_STABLE MOODLE_402_STABLE master"
  VERSIONLIST: "3.11 4.00 4.01 4.02 master"

on:
  schedule:
    # Publish every Sunday at 1:30am
    - cron: '30 1 * *  0'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Moodle
        uses: actions/checkout@v3
        with:
          repository: moodle/moodle
          path: .moodle

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.moodle/.nvmrc'

      - name: Generate all API Documentation
        run: ./scripts/generate_api_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: jsdoc.moodledev.io
