name: Generate API docs and publish to Github Pages

env:
  BRANCHLIST: "MOODLE_401_STABLE MOODLE_402_STABLE MOODLE_403_STABLE main"
  VERSIONLIST: "4.01 4.02 4.03 main"

on:
  schedule:
    # Publish every Sunday at 1:30am
    - cron: '30 1 * *  0'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: .moodle

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.moodle/.nvmrc'

      - name: Generate all API Documentation
        run: ./scripts/generate_api_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: jsdoc.moodledev.io
